#!/bin/bash

build() {
	
	add_file "/etc/vdev/vdevd.boot.conf"
	add_file "/etc/vdev/ifnames.conf"
	add_file "/usr/lib/vdev/hwdb/hwdb.squashfs"
	add_file "/etc/group"
	add_file "/etc/passwd"
	
	#soft
	add_binary /usr/bin/vdevd
	add_binary /usr/bin/MAKEDEV
	add_binary /usr/bin/dash
	
	add_symlink /usr/bin/lvm lvs
	add_symlink /usr/bin/lvm pvs
	
	add_binary /usr/bin/sed
	add_binary /usr/bin/grep
	add_binary /usr/bin/fgrep
	add_binary /usr/bin/egrep
	
	#module
	add_module squashfs
	
	#lib
	add_file /usr/lib/libc.so.6
	add_file /usr/lib/libnss_compat.so.2
	add_file /usr/lib/libnsl.so.1
	add_file /usr/lib/libnss_nis.so.2
	add_file /usr/lib/libnss_files.so.2
	
	for act in /etc/vdev/actions/*.act; do
		add_file "$act"
	done
    
	for prog in /usr/lib/vdev/*.sh; do
		add_binary "$prog"
	done
	
	#not necessary ???
	for tool in /usr/lib/vdev/stat_*; do
		add_binary "$tool"
	done
    
	add_runscript
	
}

help() {
    cat <<HELPEOF
This hook will use vdev to create your root device node and detect the needed
modules for your root device. It is also required for firmware loading in
initramfs. It is recommended to use this hook.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
