#!/bin/bash

build() {
	
	add_file "/etc/vdev/vdevd.conf"
	add_file "/etc/vdev/ifnames.conf"
	add_file "/usr/lib/vdev/hwdb/hwdb.squashfs"
	add_file "/etc/group"
	add_file "/etc/passwd"
	
	#soft
	add_binary /usr/bin/vdevd
	add_binary /usr/bin/MAKEDEV
	add_binary /usr/bin/dash
	
	add_symlink /usr/bin/lvs /usr/bin/lvm
	add_symlink /usr/bin/pvs /usr/bin/lvm
	
	add_binary /usr/bin/sed
	add_binary /usr/bin/grep
	add_binary /usr/bin/fgrep
	add_binary /usr/bin/egrep
	
	
	#module
	add_module squashfs
	
	#lib
	add_file /usr/lib/libc.so.6  #link to ->
	add_binary /usr/lib/libc-2.22.so
	
	add_file /usr/lib/libnss_compat.so.2 #link to ->
	add_binary /usr/lib/libnss_compat-2.22.so
	
	add_file /usr/lib/libnsl.so.1 #lint to ->
	add_binary /usr/lib/libnsl-2.22.so 
	
	add_file /usr/lib/libnss_nis.so.2 #link to ->
	add_binary /usr/lib/libnss_nis-2.22.so
	
	add_file /usr/lib/libnss_files.so.2 #link to ->
	add_binary /usr/lib/libnss_files-2.22.so
	
	add_binary /usr/lib/libgcc_s.so.1
		
	for act in /etc/vdev/actions/*.act; do
		add_file "$act"
	done
    
	for prog in /usr/lib/vdev/*.sh; do
		add_binary "$prog"
	done
	add_binary /usr/lib/vdev/daemonlet
	
	#not necessary ???
	for tool in /usr/lib/vdev/stat_*; do
		add_binary "$tool"
	done
    
	add_runscript
	
}

help() {
    cat <<HELPEOF
This hook will use vdev to create your root device node and detect the needed
modules for your root device. It is also required for firmware loading in
initramfs. It is recommended to use this hook.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
