#!/usr/bin/ash

run_earlyhook() {
	
	#module need to be loaded before launching vdevd
	modprobe -a hid_generic usbhid hid sd_mod xhci_pci xhci_hcd ahci libahci ehci_pci libata ehci_hcd scsi_mod usbcore usb_common

}

run_hook() {

	/usr/bin/vdevd -c /etc/vdev/vdevd.boot.conf -l /run/vdevd.boot.log -v2 /dev 

}

run_cleanuphook() {

	kill $(pidof vdevd)
	rm /run/vdevd.boot.pid

}

# vim: set ft=sh ts=4 sw=4 et:
